version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
        - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    image: redis
    ports:
      - "6379:6379"
    # volumes:
    #   - ./redis:/data/db

  web:
    build: .
    # env_file:
    #   - dev.env
    command: ./run_django.sh
    volumes:
      - .:/src
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  celery:
    build: .
    command: celery -A dathena worker -l info
    # command: >
    #   bash -c "sleep 60
    #   && celery -A dathena worker -l info"
    volumes:
      - .:/src
    depends_on:
      - db
      - redis

  celerybeat:
    build: .
    command: >
      bash -c "rm -f celerybeat.pid
      && celery -A dathena beat -l info"
    # command: celery -A dathena beat -l info
    volumes:
      - .:/src
    depends_on:
      - db
      - redis


volumes:
  postgres_data:
