version: '3'

services:
  db:
    image: postgres

  redis:
    image: redis
    ports:
      - "6379:6379"

  web:
    build: .
    command: ./run_django.sh
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  celery:
    build: .
    command: celery -A dathena worker -l info
    volumes:
      - .:/src
    depends_on:
      - db
      - redis

  celerybeat:
    build: .
    command: >
      bash -c "rm -f celerybeat.pid
      && celery -A dathena beat -l info"
    volumes:
      - .:/src
    depends_on:
      - db
      - redis
