# Generated by Django 2.0.9 on 2018-10-30 12:27

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Confidentiality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('short_name', models.CharField(max_length=255, unique=True, verbose_name='Short Name')),
                ('authority_level', models.PositiveSmallIntegerField(default=1, verbose_name='Authority')),
                ('total_docs', models.IntegerField(default=0, verbose_name='Total Docs')),
            ],
            options={
                'verbose_name': 'Confidentiality',
                'verbose_name_plural': 'Confidentiality',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('file', models.FileField(max_length=255, upload_to='uploads/', verbose_name='Document')),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, size=None)),
                ('confidentiality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doc_condifentuality', to='documents.Confidentiality')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
            },
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('short_name', models.CharField(max_length=255, unique=True, verbose_name='Short Name')),
                ('total_docs', models.IntegerField(default=0, verbose_name='Total Docs')),
            ],
            options={
                'verbose_name': 'Document Type',
                'verbose_name_plural': 'Document Types',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('short_name', models.CharField(max_length=255, unique=True, verbose_name='Short Name')),
                ('total_docs', models.IntegerField(default=0, verbose_name='Total Docs')),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
            },
        ),
        migrations.AddField(
            model_name='document',
            name='document_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doc_documenttype', to='documents.DocumentType'),
        ),
        migrations.AddField(
            model_name='document',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doc_langauge', to='documents.Language'),
        ),
        migrations.AddField(
            model_name='document',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doc_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
